# Generated by Django 4.1.7 on 2025-06-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_addr",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_class",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_fathername",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_gender",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_mothername",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="s_school",
        ),
        migrations.RemoveField(
            model_name="student",
            name="updated_at",
        ),
    ]
